### ISSUE TITLE
Error in creating the environment

### ISSUE THREAD

**Issue by luckcolors** [mumble-voip/mumble-releng#13]
Hello
I've got a problem i creating the enviroment when i execute the command in mumblebuild cygwin i get this error. Here's the log. I hope you can help me.

+ ./nasm-binary.build
/usr/bin/env: mumble-build: No such file or directory

**Comment by mkrautz** [comment]
Are you trying to execute ./nasm-binary.build directoy, or are you doing it through the build-all.bash script?

**Comment by luckcolors** [comment]
no i'm using build-all.bash 
i just didn't copied the full log.

**Comment by mkrautz** [comment]
How are you executing build-all.bash?

As you can see from build-all.bash, it tries to add the home of the mumble-build script to the PATH environment variable:

    export MUMBLE_RELENG_ROOT=$(git rev-parse --show-toplevel)
    export PATH=${MUMBLE_RELENG_ROOT}/mumble-build:${PATH}

Try echo'ing $MUMBLE_RELENG_ROOT and $PATH and see if those look OK?

**Comment by luckcolors** [comment]
$MUMBLE_RELENG_ROOT doesn't emit an output.
Also i'm using cygwin64 from another hdd D: i mklinked the cygwin64 folder to C: i don't think this is causing the error.

**Comment by luckcolors** [comment]
Also i'm using a previous install (up to date) of mklinked from my D: drive to C:\cygwin64.
Could this cause the problem?

**Comment by mkrautz** [comment]
Did you also add MUMBLE_RELENG_ROOT to the PATH?

    export PATH=${MUMBLE_RELENG_ROOT}/mumble-build:${PATH}

?

**Comment by luckcolors** [comment]
yes i tried 
but i notice that the MUMBLE_RELENG_ROOT is in the windows path format not linux one C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble-releng/mumble-build i tried to export it in the linux format but id didn't work. here's my path with the commands i executed:

Luckcolors@Luckcolors-PC /cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-5
87ee03/mumble-releng/buildenv/1.3.x/win32-static
$ export MUMBLE_RELENG_ROOT=/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-
19-587ee03/mumble-releng/mumble-build

Luckcolors@Luckcolors-PC /cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-5
87ee03/mumble-releng/buildenv/1.3.x/win32-static
$ export PATH=${MUMBLE_RELENG_ROOT}/mumble-build:${PATH}

Luckcolors@Luckcolors-PC /cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-5
87ee03/mumble-releng/buildenv/1.3.x/win32-static
$ ./build-all.bash
++ git rev-parse --show-toplevel
+ export MUMBLE_RELENG_ROOT=C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03
/mumble-releng
+ MUMBLE_RELENG_ROOT=C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble
-releng
+ export 'PATH=C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble-relen
g/mumble-build:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mum
ble-releng/mumble-build/mumble-build:/cygdrive/c/MumbleBuild/win32-static-1.3.x-
2015-05-19-587ee03/ZeroC-Ice/bin:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015
-05-19-587ee03/protobuf/vsprojects/Release:/cygdrive/c/MumbleBuild/win32-static-
1.3.x-2015-05-19-587ee03/jom/bin:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015
-05-19-587ee03/OpenSSL/bin:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19
-587ee03/Qt5/bin:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/n
asm:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/perl/perl/bin:
/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/perl/perl/site/bin
:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/python:/cygdrive/
c/Program Files (x86)/Microsoft DirectX SDK (June 2010)/Utilities/Bin/x64:/cygdr
ive/c/Program Files (x86)/Microsoft DirectX SDK (June 2010)/Utilities/Bin/x86:/c
ygdrive/c/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Bin:/cygdrive/c/Progr
am Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/CommonExtensions/Microso
ft/TestWindow:/cygdrive/c/Program Files (x86)/Microsoft SDKs/F#/3.1/Framework/v4
.0:/cygdrive/c/Program Files (x86)/MSBuild/12.0/bin:/cygdrive/c/Program Files (x
86)/Microsoft Visual Studio 12.0/Common7/IDE:/cygdrive/c/Program Files (x86)/Mic
rosoft Visual Studio 12.0/VC/BIN:/cygdrive/c/Program Files (x86)/Microsoft Visua
l Studio 12.0/Common7/Tools:/cygdrive/c/Windows/Microsoft.NET/Framework64/v4.0.3
0319:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/VCPackages:
/cygdrive/c/Program Files (x86)/HTML Help Workshop:/cygdrive/c/Program Files (x8
6)/Microsoft Visual Studio 12.0/Team Tools/Performance Tools:/cygdrive/c/Program
 Files (x86)/Windows Kits/8.1/bin/x86:/cygdrive/c/Program Files (x86)/Microsoft
SDKs/Windows/v8.1A/bin/NETFX 4.5.1 Tools:/usr/local/bin:/usr/bin:/cygdrive/d/Pro
gram Files (x86)/CollabNet:/cygdrive/c/EnvironmentPath/Python34:/cygdrive/c/Envi
ronmentPath/Python34/Scripts:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdr
ive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cygdrive/c/Windows/sy
stem32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows
/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Microsoft SQL Server/
110/Tools/Binn:/cygdrive/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0:/cy
gdrive/c/Program Files/Microsoft SQL Server/120/Tools/Binn:/cygdrive/c/Environme
ntPath/go/bin:/cygdrive/c/Program Files (x86)/Git/cmd:/cygdrive/c/Program Files/
Microsoft Windows Performance Toolkit:/cygdrive/d/Program Files/TortoiseSVN/bin:
/cygdrive/c/Program Files (x86)/CMake/bin:/cygdrive/c/EnvironmentPath/wget:/cygd
rive/c/Program Files/TortoiseHg:/cygdrive/c/EnvironmentPath/apache-maven/bin:/cy
gdrive/c/EnvironmentPath/apache-ant/bin:/cygdrive/c/Program Files/7-Zip:/cygdriv
e/c/EnvironmentPath/HashiCorp/Vagrant/bin:/cygdrive/c/EnvironmentPath/Heroku/bin
:/cygdrive/c/Program Files (x86)/git/cmd:/cygdrive/c/EnvironmentPath/php-5.6.8:/
cygdrive/c/ProgramData/ComposerSetup/bin:/cygdrive/c/EnvironmentPath/Emscripten/
clang/e1.29.0_64bit:/cygdrive/c/EnvironmentPath/Emscripten/node/0.10.17_64bit:/c
ygdrive/c/EnvironmentPath/Emscripten/python/2.7.5.3_64bit:/cygdrive/c/Environmen
tPath/Emscripten/java/7.45_64bit/bin:/cygdrive/c/EnvironmentPath/Emscripten:/cyg
drive/c/EnvironmentPath/Emscripten/emscripten/1.29.0:/cygdrive/c/EnvironmentPath
/Emscripten/crunch/1.03:/cygdrive/c/EnvironmentPath/Emscripten/mingw/4.6.2_32bit
:/cygdrive/c/EnvironmentPath/Bazaar:/cygdrive/c/Program Files (x86)/Skype/Phone:
/cygdrive/c/EnvironmentPath/doxygen/bin:/cygdrive/c/Program Files (x86)/Spoon/Cm
d:/cygdrive/d/Program Files/iojs:/cygdrive/d/Program Files/nodejs:%USERPROFILE%/
.dnx/bin:/cygdrive/c/Program Files/Microsoft DNX/Dnvm:/cygdrive/c/Program Files
(x86)/Windows Kits/10/Windows Performance Toolkit:/cygdrive/c/Program Files (x86
)/Windows Kits/8.1/Windows Performance Toolkit:/cygdrive/c/EnvironmentPath/Boot2
Docker for Windows:/cygdrive/c/EnvironmentPath/curl:/cygdrive/c/EnvironmentPath/
premake:/cygdrive/c/EnvironmentPath/go_tools:/cygdrive/c/Users/Luckcolors/AppDat
a/Roaming/npm:/cygdrive/c/Users/Luckcolors/AppData/Local/Code/bin'
+ PATH='C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble-releng/mumbl
e-build:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble-rel
eng/mumble-build/mumble-build:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05
-19-587ee03/ZeroC-Ice/bin:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-
587ee03/protobuf/vsprojects/Release:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2
015-05-19-587ee03/jom/bin:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-
587ee03/OpenSSL/bin:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee0
3/Qt5/bin:/cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/nasm:/cy
gdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/perl/perl/bin:/cygdri
ve/c/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/perl/perl/site/bin:/cygdr
ive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/python:/cygdrive/c/Progr
am Files (x86)/Microsoft DirectX SDK (June 2010)/Utilities/Bin/x64:/cygdrive/c/P
rogram Files (x86)/Microsoft DirectX SDK (June 2010)/Utilities/Bin/x86:/cygdrive
/c/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Bin:/cygdrive/c/Program File
s (x86)/Microsoft Visual Studio 12.0/Common7/IDE/CommonExtensions/Microsoft/Test
Window:/cygdrive/c/Program Files (x86)/Microsoft SDKs/F#/3.1/Framework/v4.0:/cyg
drive/c/Program Files (x86)/MSBuild/12.0/bin:/cygdrive/c/Program Files (x86)/Mic
rosoft Visual Studio 12.0/Common7/IDE:/cygdrive/c/Program Files (x86)/Microsoft
Visual Studio 12.0/VC/BIN:/cygdrive/c/Program Files (x86)/Microsoft Visual Studi
o 12.0/Common7/Tools:/cygdrive/c/Windows/Microsoft.NET/Framework64/v4.0.30319:/c
ygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/VCPackages:/cygdri
ve/c/Program Files (x86)/HTML Help Workshop:/cygdrive/c/Program Files (x86)/Micr
osoft Visual Studio 12.0/Team Tools/Performance Tools:/cygdrive/c/Program Files
(x86)/Windows Kits/8.1/bin/x86:/cygdrive/c/Program Files (x86)/Microsoft SDKs/Wi
ndows/v8.1A/bin/NETFX 4.5.1 Tools:/usr/local/bin:/usr/bin:/cygdrive/d/Program Fi
les (x86)/CollabNet:/cygdrive/c/EnvironmentPath/Python34:/cygdrive/c/Environment
Path/Python34/Scripts:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/P
rogram Files (x86)/NVIDIA Corporation/PhysX/Common:/cygdrive/c/Windows/system32:
/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System
32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Microsoft SQL Server/110/Too
ls/Binn:/cygdrive/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0:/cygdrive/
c/Program Files/Microsoft SQL Server/120/Tools/Binn:/cygdrive/c/EnvironmentPath/
go/bin:/cygdrive/c/Program Files (x86)/Git/cmd:/cygdrive/c/Program Files/Microso
ft Windows Performance Toolkit:/cygdrive/d/Program Files/TortoiseSVN/bin:/cygdri
ve/c/Program Files (x86)/CMake/bin:/cygdrive/c/EnvironmentPath/wget:/cygdrive/c/
Program Files/TortoiseHg:/cygdrive/c/EnvironmentPath/apache-maven/bin:/cygdrive/
c/EnvironmentPath/apache-ant/bin:/cygdrive/c/Program Files/7-Zip:/cygdrive/c/Env
ironmentPath/HashiCorp/Vagrant/bin:/cygdrive/c/EnvironmentPath/Heroku/bin:/cygdr
ive/c/Program Files (x86)/git/cmd:/cygdrive/c/EnvironmentPath/php-5.6.8:/cygdriv
e/c/ProgramData/ComposerSetup/bin:/cygdrive/c/EnvironmentPath/Emscripten/clang/e
1.29.0_64bit:/cygdrive/c/EnvironmentPath/Emscripten/node/0.10.17_64bit:/cygdrive
/c/EnvironmentPath/Emscripten/python/2.7.5.3_64bit:/cygdrive/c/EnvironmentPath/E
mscripten/java/7.45_64bit/bin:/cygdrive/c/EnvironmentPath/Emscripten:/cygdrive/c
/EnvironmentPath/Emscripten/emscripten/1.29.0:/cygdrive/c/EnvironmentPath/Emscri
pten/crunch/1.03:/cygdrive/c/EnvironmentPath/Emscripten/mingw/4.6.2_32bit:/cygdr
ive/c/EnvironmentPath/Bazaar:/cygdrive/c/Program Files (x86)/Skype/Phone:/cygdri
ve/c/EnvironmentPath/doxygen/bin:/cygdrive/c/Program Files (x86)/Spoon/Cmd:/cygd
rive/d/Program Files/iojs:/cygdrive/d/Program Files/nodejs:%USERPROFILE%/.dnx/bi
n:/cygdrive/c/Program Files/Microsoft DNX/Dnvm:/cygdrive/c/Program Files (x86)/W
indows Kits/10/Windows Performance Toolkit:/cygdrive/c/Program Files (x86)/Windo
ws Kits/8.1/Windows Performance Toolkit:/cygdrive/c/EnvironmentPath/Boot2Docker
for Windows:/cygdrive/c/EnvironmentPath/curl:/cygdrive/c/EnvironmentPath/premake
:/cygdrive/c/EnvironmentPath/go_tools:/cygdrive/c/Users/Luckcolors/AppData/Roami
ng/npm:/cygdrive/c/Users/Luckcolors/AppData/Local/Code/bin'
+ ./nasm-binary.build
/usr/bin/env: mumble-build: No such file or directory

Luckcolors@Luckcolors-PC /cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-5
87ee03/mumble-releng/buildenv/1.3.x/win32-static

**Comment by mkrautz** [comment]
Ah, OK.

So it seems build-all.bash expects that the Git binary it is using is the Cygwin one.

You don't have Git installed via Cygwin, so it uses, presumably, msysgit.  That gives us Windows paths back.

**Comment by mkrautz** [comment]
As a workaround, you should be able to add the Cygwin-style path of the mumble-build in mumble-releng to your path. That should make it work - I think.

**Comment by luckcolors** [comment]
OK for future reference i fixed this bug by installing git by the cygwin setup.

**Comment by luckcolors** [comment]
But now i get a different bug:
C:\MumbleBuild is a windows symlink to C:\Users\Luckcolors\MumbleBuild
As said by setup.cmd

mkdir -p /cygdrive/c/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/nasm/

**Comment by luckcolors** [comment]
when fetching jom curl refuses the certificate.
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
+ '[' 60 -eq 0 ']'
+ rm -f jom_1_0_14.zip
+ set -e
+ '[' '!' -f jom_1_0_14.zip ']'
+ echo 'Unable to fetch file '\''jom_1_0_14.zip'\''...'
Unable to fetch file 'jom_1_0_14.zip'...
+ exit 1

**Comment by mkrautz** [comment]
I believe there is a ca-certificates (or equivalent) package in Cygwin.

**Comment by mkrautz** [comment]
BTW -

The easiest way to grab all the deps for your Cygwin install would be to put your setup.exe into the cygwin-deps folder:

https://github.com/mumble-voip/mumble-releng/tree/master/buildenv/1.3.x/win32-static/cygwin-deps

and running the batch script in there.

That'll install all the known required dependencies.

**Comment by mkrautz** [comment]
Alternatively, the required deps are listed in that file...

**Comment by luckcolors** [comment]
ok i fixed thanks for your help.
