### ISSUE TITLE
Error in qmake.

### ISSUE THREAD

**Issue by luckcolors** [mumble-voip/mumble-releng#14]
Hello.
I finally finished to build the dependencies using x64 env.
I'm using the MumbleBuild - Cmd
Also i have got a install of qt.(just for info)
but when i run qmake i get this error log:
C:\MumbleBuild\win32-static-1.3.x-2015-05-19-587ee03\mumble>qmake -recursive mai
n.pro CONFIG+="release static no-elevation no-g15 no-asio" CONFIG-=sse2
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/3rdparty/spe
ex-build/speex-build.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/3rdparty/cel
t-0.7.0-build/celt-0.7.0-build.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/3rdparty/cel
t-0.11.0-build/celt-0.11.0-build.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/3rdparty/opu
s-build/opus-build.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/3rdparty/min
hook-build/minhook-build.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/src/mumble/m
umble.pro
Project MESSAGE: This project is using private headers and will therefore be tie
d to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules m
ay crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have
 been warned!
WARNING: Failure to find: qt_cs.qm
WARNING: Failure to find: qt_da.qm
WARNING: Failure to find: qt_de.qm
WARNING: Failure to find: qt_es.qm
WARNING: Failure to find: qt_fr.qm
WARNING: Failure to find: qt_he.qm
WARNING: Failure to find: qt_hu.qm
WARNING: Failure to find: qt_ja.qm
WARNING: Failure to find: qt_pl.qm
WARNING: Failure to find: qt_pt.qm
WARNING: Failure to find: qt_ru.qm
WARNING: Failure to find: qt_sv.qm
WARNING: Failure to find: qt_zh_CN.qm
WARNING: Failure to find: qt_zh_TW.qm
WARNING: Failure to find: qt_cs.qm
WARNING: Failure to find: qt_da.qm
WARNING: Failure to find: qt_de.qm
WARNING: Failure to find: qt_es.qm
WARNING: Failure to find: qt_fr.qm
WARNING: Failure to find: qt_he.qm
WARNING: Failure to find: qt_hu.qm
WARNING: Failure to find: qt_ja.qm
WARNING: Failure to find: qt_pl.qm
WARNING: Failure to find: qt_pt.qm
WARNING: Failure to find: qt_ru.qm
WARNING: Failure to find: qt_sv.qm
WARNING: Failure to find: qt_zh_CN.qm
WARNING: Failure to find: qt_zh_TW.qm
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_cs.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_cy.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_da.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_de.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_el.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_en.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_en_GB.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_eo.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_es.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_eu.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_fa_IR.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_fi.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_fr.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_gl.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_he.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_hu.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_it.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_ja.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_ko.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_lt.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_nl.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_no.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_pl.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_pt_BR.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_pt_PT.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_ru.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_sk.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_sv.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_th.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_tr.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_vi.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_zh_CN.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_zh_TW.qm'
RCC: Warning: No resources in 'mumble_translations.qrc'.
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_cs.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_da.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_de.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_es.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_fr.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_he.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_hu.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qttranslations/qt_it.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_ja.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qttranslations/qt_nl.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_pl.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_pt.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_ru.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_sv.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qttranslations/qt_tr.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_zh_CN.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_zh_TW.qm'
RCC: Warning: No resources in 'mumble_qt.qrc'.
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_cs.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_cy.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_da.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_de.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_el.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_en.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_en_GB.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_eo.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_es.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_eu.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_fa_IR.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_fi.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_fr.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_gl.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_he.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_hu.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_it.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_ja.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_ko.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_lt.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_nl.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_no.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_pl.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_pt_BR.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_pt_PT.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_ru.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_sk.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_sv.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_th.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_tr.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_vi.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_zh_CN.qm'
RCC: Error in 'mumble_translations.qrc': Cannot find file 'mumble_zh_TW.qm'
RCC: Warning: No resources in 'mumble_translations.qrc'.
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_cs.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_da.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_de.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_es.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_fr.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_he.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_hu.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qttranslations/qt_it.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_ja.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qttranslations/qt_nl.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_pl.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_pt.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_ru.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_sv.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qttranslations/qt_tr.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_zh_CN.qm'
RCC: Error in 'mumble_qt.qrc': Cannot find file 'qt_zh_TW.qm'
RCC: Warning: No resources in 'mumble_qt.qrc'.
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/src/mumble_e
xe/mumble_exe.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/plug
ins.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/lin
k/link.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/man
ual/manual.pro
Project MESSAGE: This project is using private headers and will therefore be tie
d to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules m
ay crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have
 been warned!
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/aoc
/aoc.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/arm
a2/arma2.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/bf1
942/bf1942.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/bf2
/bf2.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/bf3
/bf3.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/bf2
142/bf2142.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/bfb
c2/bfbc2.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/bfh
eroes/bfheroes.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/bla
cklight/blacklight.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/bor
derlands/borderlands.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/bor
derlands2/borderlands2.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/bre
ach/breach.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/cod
2/cod2.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/cod
4/cod4.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/cod
5/cod5.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/cod
mw2/codmw2.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/cod
mw2so/codmw2so.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/cs/
cs.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/css
/css.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/dod
s/dods.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/dys
/dys.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/etq
w/etqw.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/tf2
/tf2.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/gmo
d/gmod.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/gta
iv/gtaiv.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/gw/
gw.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/hl2
dm/hl2dm.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/ins
urgency/insurgency.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/jc2
/jc2.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/l4d
/l4d.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/l4d
2/l4d2.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/lol
/lol.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/lot
ro/lotro.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/sr/
sr.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/sto
/sto.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/ut2
004/ut2004.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/ut3
/ut3.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/ut9
9/ut99.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/wol
fet/wolfet.pro
 Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/plugins/wow
/wow.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/3rdparty/fx1
1-build-x86/fx11-build-x86.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/3rdparty/fx1
1-build-x64/fx11-build-x64.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/overlay/over
lay.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/overlay/over
lay_exe/overlay_exe.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/overlay_winx
64/overlay_winx64.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/overlay_winx
64/overlay_exe_winx64/overlay_exe_winx64.pro
Reading C:/MumbleBuild/win32-static-1.3.x-2015-05-19-587ee03/mumble/src/murmur/m
urmur.pro
Project WARNING: Plugin class name could not be determined for qcleanlooksstyle
plugin.
Project WARNING: Plugin class name could not be determined for qmotifstyle plugi
n.
Project WARNING: Plugin class name could not be determined for qplastiquestyle p
lugin.
Project WARNING: Plugin class name could not be determined for qcleanlooksstyle
plugin.
Project WARNING: Plugin class name could not be determined for qmotifstyle plugi
n.
Project WARNING: Plugin class name could not be determined for qplastiquestyle p
lugin.
Project WARNING: Plugin class name could not be determined for qcleanlooksstyle
plugin.
Project WARNING: Plugin class name could not be determined for qmotifstyle plugi
n.
Project WARNING: Plugin class name could not be determined for qplastiquestyle p
lugin.

**Comment by mkrautz** [comment]
Those should be harmless.  You should be able to run nmake/jom just fine.
