### ISSUE TITLE
OS X buildenv does not work due to missing OpenSSL files

### ISSUE THREAD

**Issue by pxk7062** [mumble-voip/mumble-releng#20]
The file "http://releng-distfiles.mumble.info/releng-distfiles/openssl-1.0.2e.tar.gz" is missing.
This was added in:
https://github.com/mumble-voip/mumble-releng/commit/4d2eb403eba902a232899e06ae20320440e3a00a
 https://github.com/mumble-voip/mumble-releng/commit/db9f6129c0319aee9d98b5ceb2cc5894247027b4

**Comment by mkrautz** [comment]
Not sure what the problem is? The build recipes fall back to the official mirror, so it should work fine.

What problem are you seeing?

**Comment by pxk7062** [comment]
I took out all the links to the releng site and I stopped getting missing development package errors. Didn't explore too much but I did make a post of it on the mumble forum. 

https://forums.mumble.info/viewtopic.php?f=4&t=2875&p=7594#p7594

If there's something I'm missing please let me know.

**Comment by mkrautz** [comment]
If you look later on in your log, you should notice that it will presumably have downloaded OpenSSL from the official mirror after that.

I don't know what's wrong with your build environment, but here's something you can try:

(Substituting ${NameOfYourEnv} with the real directory...)

    $ source /MumbleBuild/${NameOfYourEnv}/env
    $ cd /MumbleBuild/${NameOfYourEnv}/mumble-releng/buildenv/1.3.x/osx
    $ export MUMBLE_RELENG_ROOT=$(git rev-parse --show-toplevel)
    $ export PATH=${MUMBLE_RELENG_ROOT}/mumble-build:${PATH}
    $ ./openssl.build

This should build OpenSSL only. Then you can inspect the build output, and see what's wrong, or post it here.

**Comment by mkrautz** [comment]
@pxk7062 Any news on this from you? Did my suggestion work?

**Comment by pxk7062** [comment]
It didn't look like it grabbed anything from the second link. I redid the build environment and tried it again, but didn't work. What ended up working was removing the link. If anyone comes across this issue this might be helpful to try out.

**Comment by mkrautz** [comment]
See resolution of https://github.com/mumble-voip/mumble-releng/issues/22

If this is still broken for you, please respond here, or open a new ticket. Thanks!
