### ISSUE TITLE
Openssl build script for win32 static has invalid links

### ISSUE THREAD

**Issue by Vistritium** [mumble-voip/mumble-releng#22]
https://github.com/mumble-voip/mumble-releng/blob/5697a589a54ed9d727f9551f680ad625e0b73855/buildenv/1.3.x/win32-static/openssl.build#L8-L9

Urls return 404

**Comment by mkrautz** [comment]
The URLs are tried in order. If one fails, it'll fallback to the next one.
The idea is we can mirror the files if we must. This is nice, especially when a particular build environment has been deployed to a builder -- and upstream removes the original file we linked to.
Then we can just upload a copy to our mirror, and the build will work again.

So, the extra URLs are simply there as a safety belt for us.

Did you experience any problems with this? We've received multiple reports of this, but I don't quite see why the 404'ing URLs are causing so many problems for people.

**Comment by wbv** [comment]
The issue I'm seeing is that the requests don't 404, they just take forever. The build scripts call curl using:

` curl -f -L -o `

Which doesn't account for any sort of timeout. The fallback system is nice (and clever) but most of the requests I see to `https://releng-distfiles.mumble.info` take several minutes to reply. Perhaps a 30 second timeout would allieviate most of the complaints? i.e.

`curl -f -L --connect-timeout 30 -o `

**Comment by mkrautz** [comment]
Sounds good to me.

**Comment by mkrautz** [comment]
I've added this in https://github.com/mumble-voip/mumble-releng/commit/9dccbd49438e4b550dba8792e2ad9f5f0ee34d0c

I've also ensured that the releng-distfiles mirror is more up-to-date now than it was previously.
