### ISSUE TITLE
Mumble build window cygwin64 doesn't work

### ISSUE THREAD

**Issue by gaffo** [mumble-voip/mumble-releng#25]
$ ./build-all.bash
- echo 'The win64-static build environment is maintained '
  The win64-static build environment is maintained
- echo 'in the same directory as the win32-static build '
  in the same directory as the win32-static build
- echo environment.
  environment.
- echo
- echo 'I will automatically change to the win32-static directory '
  I will automatically change to the win32-static directory
- echo 'and call the win32-static '\''build-all.bash'\'' to initiate '
  and call the win32-static 'build-all.bash' to initiate
- echo 'the win64-static build.'
  the win64-static build.
- cd ../win32-static
- ./build-all.bash
- ./nasm-binary.build
  ++ git rev-parse --show-toplevel
- RELENG_ROOT=C:/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650/mumble-releng
- '[' C:/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650/mumble-releng '!=' 'C:\MumbleBuild\win64-static-1.3.x-2016-06-11-6ba4b84-650\mumble-releng' ']'
- export MUMBLE_RELENG_ROOT=C:/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650/mumble-releng
- MUMBLE_RELENG_ROOT=C:/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650/mumble-releng
- MUMBLE_BUILD=C:/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650/mumble-releng/mumble-build/mumble-build
- echo 'Using mumble-build script at '\''C:/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650/mumble-releng/mumble-build/mumble-build'\'' instead.'
  Using mumble-build script at 'C:/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650/mumble-releng/mumble-build/mumble-build' instead.
- set +e
- C:/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650/mumble-releng/mumble-build/mumble-build ./nasm-binary.build
  ++ git rev-parse --show-toplevel
- RELENG_ROOT=C:/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650/mumble-releng
- '[' C:/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650/mumble-releng '!=' C:/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650/mumble-releng ']'
- '[' /cygdrive/c/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650 == '' ']'
- '[' /cygdrive/c/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650.build == '' ']'
- . ./nasm-binary.build
  ++ urls=("http://releng-distfiles.mumble.info/releng-distfiles/nasm-2.11-win32.zip" "http://www.nasm.us/pub/nasm/releasebuilds/2.11/win32/nasm-2.11-win32.zip")
  ++ digests=("sha1:d02cd111fc74daaf901a714d4d325fef5f769224" "sha256:abcad8089bdf03c10e0cd621415ae71cd8289d346000ee8b1e8aaf27f6d98de9")
- '[' 12.0 '!=' '' ']'
  ++ echo 12.0
  ++ sed 's,.0,,'
- VSMAJOR=12
- [[ 12 -gt 11 ]]
- [[ amd64 == \x\8\6 ]]
- MUMBLE_BUILDENV_ROOT=/cygdrive/c/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650/mumble-releng/buildenv/1.3.x/win32-static
- cd /cygdrive/c/MumbleBuild/win64-static-1.3.x-2016-06-11-6ba4b84-650.build
- vet
- '[' 2 -gt 0 ']'
  ++ __urlpath http://releng-distfiles.mumble.info/releng-distfiles/nasm-2.11-win32.zip
  +++ basename http://releng-distfiles.mumble.info/releng-distfiles/nasm-2.11-win32.zip
  +++ sed 's,.*#fn=,,'
  ++ realfn=nasm-2.11-win32.zip
  ++ '[' nasm-2.11-win32.zip == '' ']'
  ++ echo nasm-2.11-win32.zip
- fn=nasm-2.11-win32.zip
- for url in '"${urls[@]}"'
  ++ __urlpath http://releng-distfiles.mumble.info/releng-distfiles/nasm-2.11-win32.zip
  +++ basename http://releng-distfiles.mumble.info/releng-distfiles/nasm-2.11-win32.zip
  +++ sed 's,.*#fn=,,'
  ++ realfn=nasm-2.11-win32.zip
  ++ '[' nasm-2.11-win32.zip == '' ']'
  ++ echo nasm-2.11-win32.zip
- urlfn=nasm-2.11-win32.zip
- '[' nasm-2.11-win32.zip '!=' nasm-2.11-win32.zip ']'
- for url in '"${urls[@]}"'
  ++ __urlpath http://www.nasm.us/pub/nasm/releasebuilds/2.11/win32/nasm-2.11-win32.zip
  +++ basename http://www.nasm.us/pub/nasm/releasebuilds/2.11/win32/nasm-2.11-win32.zip
  +++ sed 's,.*#fn=,,'
  ++ realfn=nasm-2.11-win32.zip
  ++ '[' nasm-2.11-win32.zip == '' ']'
  ++ echo nasm-2.11-win32.zip
- urlfn=nasm-2.11-win32.zip
- '[' nasm-2.11-win32.zip '!=' nasm-2.11-win32.zip ']'
- fetch
- '[' 2 -eq 0 ']'
  ++ __urlpath http://releng-distfiles.mumble.info/releng-distfiles/nasm-2.11-win32.zip
  +++ basename http://releng-distfiles.mumble.info/releng-distfiles/nasm-2.11-win32.zip
  +++ sed 's,.*#fn=,,'
  ++ realfn=nasm-2.11-win32.zip
  ++ '[' nasm-2.11-win32.zip == '' ']'
  ++ echo nasm-2.11-win32.zip
- fn=nasm-2.11-win32.zip
- '[' '!' -s nasm-2.11-win32.zip ']'
- '[' -f nasm-2.11-win32.zip ']'
- '[' '!' -f nasm-2.11-win32.zip ']'
- set +e
- for url in '"${urls[@]}"'
- curl --connect-timeout 30 -f -L -o nasm-2.11-win32.zip http://releng-distfiles.mumble.info/releng-distfiles/nasm-2.11-win32.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  100  422k  100  422k    0     0   351k      0  0:00:01  0:00:01 --:--:--  361k
- '[' 0 -eq 0 ']'
- break
- set -e
- '[' '!' -f nasm-2.11-win32.zip ']'
- '[' '!' -s nasm-2.11-win32.zip ']'
- verify
- '[' 2 -eq 0 ']'
  ++ which sha1sum
- '[' /usr/bin/sha1sum '!=' '' ']'
- SHA1_CMD=sha1sum
  ++ which sha256sum
- '[' /usr/bin/sha256sum '!=' '' ']'
- SHA256_CMD=sha256sum
  ++ basename http://releng-distfiles.mumble.info/releng-distfiles/nasm-2.11-win32.zip
- fn=nasm-2.11-win32.zip
- for digest in '"${digests[@]}"'
- '[' sha1: == sha1: ']'
  ++ sha1sum nasm-2.11-win32.zip
  ++ cut -b -40
- '[' sha1:d02cd111fc74daaf901a714d4d325fef5f769224 '!=' sha1:d02cd111fc74daaf901a714d4d325fef5f769224 ']'
- '[' sha1:d0 == sha256: ']'
- for digest in '"${digests[@]}"'
- '[' sha25 == sha1: ']'
- '[' sha256: == sha256: ']'
  ++ sha256sum nasm-2.11-win32.zip
  ++ cut -b -64
- '[' sha256:abcad8089bdf03c10e0cd621415ae71cd8289d346000ee8b1e8aaf27f6d98de9 '!=' sha256:abcad8089bdf03c10e0cd621415ae71cd8289d346000ee8b1e8aaf27f6d98de9 ']'
- extract
- unzip -q -o nasm-2.11-win32.zip
    3 [main] unzip (18096) C:\Program Files\Git\usr\bin\unzip.exe: **\* fatal error - cygheap base mismatch detected - 0x18033E400/0x180330400.
  This problem is probably due to using incompatible versions of the cygwin DLL.
  Search for cygwin1.dll using the Windows Start->Find/Search facility
  and delete all but the most recent version.  The most recent version _should_
  reside in x:\cygwin\bin, where 'x' is the drive on which you have
  installed the cygwin distribution.  Rebooting is also suggested if you
  are unable to find another cygwin DLL.
- exit 127

**Comment by gaffo** [comment]
Trying to build against cygwin64 fails with the above output. Brand new computer, brand new cygwin install

**Comment by mkrautz** [comment]
The problem seems to be that it picks up your Windows git's unzip instead of cygwin's own.

Did you install all the required deps in Cygwin?

I believe the buildenv script inserts the Cygwin bin folder quite early in the PATH env var, but I suppose your Windows Git might take precedence. I usually install Windows Git without the option to add all the utilities to my PATH so I guess that's why I haven't seen this.

**Comment by gaffo** [comment]
I'll check. Any chance it would work with Windows git and not cygwin?

**Comment by mkrautz** [comment]
So, a workaround for now might be to change the PATH variable in the buildenv. Either in the scripts themselves, or by removing the Windows Git entry from PATH before invoking build-all.bash

Or by re-installing Windows Git such that the Unix utils aren't directly exposed to Windows's come.exe.

Obviously both workarounds that should work until mumble-releng considers this case.

**Comment by mkrautz** [comment]
It can work with Windows Git. But apparently Git's bundled msys tools clash with Cygwin.

You should be able to use it as long as those tools aren't exposed in your PATH.

**Comment by gaffo** [comment]
I mean, given I have git installed, do I have to install cygwin at all?

**Comment by mkrautz** [comment]
Unfortunately, I think so.

The build env requires bash, cygpath, unzip, tar, gzip, bz2, etc., and is only tested against Cygwin.
It might work with Git's MSys, but in my experience, the MSys tools try hard to do "conversion" of "/params" into "--gnu-style-params" and so forth, which have broken things for me in the past.

If there is still an issue, please feel free to ping this bug, and I'll take a look and/or re-open it.

Closing for now...

**Comment by mkrautz** [comment]
Actually, re-opening...

I promised to look into why it preferred your Git unzip over Cygwin's... :-)

**Comment by mkrautz** [comment]
From my experiments, cygin's $PATH is prepended to your Windows path. And the buildenv PATH entries are all prepended, so I believe this issue can only happen if unzip is not installed in cygwin.

Closing. If my analysis is wrong, please re-open or ping. Thanks.
