### ISSUE TITLE
Building buildenv fails on IceMX

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble-releng#46]
I built current env d219ea1 noltg with build all.

```
ObjectFactoryF.cpp
C:\MumbleBuild\win64-static-no-ltcg-1.3.x-2017-03-26-d219ea1-825.build\ice-3.6.1\cpp\include\Ice/Metrics.h(1861): error C2248: 'IceMX::Metrics::__vbaseDtor': cannot access protected member declared in class 'IceMX::Metrics' (compiling source file Metrics.cpp)
C:\MumbleBuild\win64-static-no-ltcg-1.3.x-2017-03-26-d219ea1-825.build\ice-3.6.1\cpp\include\Ice/Metrics.h(1849): note: compiler has generated 'IceMX::Metrics::__vbaseDtor' here (compiling source file Metrics.cpp)
C:\MumbleBuild\win64-static-no-ltcg-1.3.x-2017-03-26-d219ea1-825.build\ice-3.6.1\cpp\include\Ice/Metrics.h(1795): note: see declaration of 'IceMX::Metrics' (compiling source file Metrics.cpp)

**Comment by mkrautz** [comment]
Odd, I haven't gotten an error... But I've only built win32-static (not x64), recently...

**Comment by Kissaki** [comment]
I’ve had an (unresolved) error in Ice before, like, a month ago.

**Comment by mkrautz** [comment]
Also found this: https://github.com/mumble-voip/mumble-releng/issues/47

**Comment by mkrautz** [comment]
We think this is because @Kissaki was using MSVC2015U1, not update 3... He's trying to upgrade.

**Comment by Kissaki** [comment]
Was still an issue after installing update 3 with cl.exe `Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23506 for x64`. The version @mkrautz said he had installed was newer. I'll see if I'm still not up to date.

**Comment by mkrautz** [comment]
That is still the cl.exe from Update 1:
https://blogs.msdn.microsoft.com/chuckw/2015/11/30/visual-studio-2015-update-1/

**Comment by Kissaki** [comment]
Then my install seems to be fucked. 😡

**Comment by Kissaki** [comment]
After 3 days of wasting hours, I now have the CLI compiler installed (VS CPP Tools), with which I was able to compile Ice from our buildenv fine.
