### ISSUE TITLE
Protobuf test issues on Windows

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble-releng#5]
On my home machine, the protobuf tests have begun to fail.  Only a single one fails: CommandLineInterfaceTest.OutputDirectoryIsFileError

The error I get is:

..\src\google\protobuf\compiler\command_line_interface_unittest.cc(349): error: Value of: expected_substring
  Actual: "foo.proto/: Not a directory"
Expected: a substring of error_text_
Which is: "s6j4./proto2_cli_test_temp/foo.proto/foo.proto.MockCodeGenerator.test_generator: No such file or directory"

I've traced the problem down to my C: drive.  The "problem" is that ProcMon tries to open the file (using fast I/O), however, on my C: drive, fast I/O is seemingly disallowed:

![image](https://cloud.githubusercontent.com/assets/36527/3421107/a83ceece-fed8-11e3-8e4d-026513c9365d.png)

If I run the same thing on my X: drive, it succeeds:

![image](https://cloud.githubusercontent.com/assets/36527/3421121/50b8fd22-fed9-11e3-87d1-67be38a46e6a.png)

because FASTIO_NETWORK_QUERY_OPEN returns NAME INVALID immediately.

I'm trying to figure out what the correct fix for this is (hopefully just a reboot of my machine?)

**Comment by Kissaki** [comment]
The patch in question is [`protobuf-2.5.0-win32-disable-OutputDirectoryIsFileError-test.patch`](https://github.com/mumble-voip/mumble-releng/blob/1ddd96684b5d46ae2ee30baf8cbaf5b43092d2b4/buildenv/1.3.x/win32-static/patches/protobuf-2.5.0-win32-disable-OutputDirectoryIsFileError-test.patch).
