### ISSUE TITLE
Change buildenv philosophy

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble-releng#66]
In the long term, it would be nice if we changed our philosophy of our build environments.

Currently, you enter a shell to set up the correct environment. Then you build from there.

It's tedious.

A better solution would be to have the build scripts automatically pick up on build environments and use them.

**Comment by ZeroAbility** [comment]
Here is the test bed for that: https://github.com/mumble-voip/mumble-releng-experimental
Davide set it up for me to explore some ideas. I would welcome your input.

**Comment by Kissaki** [comment]
Hello @ZeroAbility 
What’s the current state of your efforts?

**Comment by ZeroAbility** [comment]
I've had some extended projects at work from the beginning of this year so I'm not as far as I'd like to be with it. Last I checked, the qt5-base package in vcpkg was not building correctly in GNU/Linux. It appears to be a lib path issue for sqlite:

https://github.com/Microsoft/vcpkg/issues/4804
https://github.com/Microsoft/vcpkg/issues/5038

I'm trying to wait to see if there are people working on it or if I need to get involved. I'd also like to get a consensus about removal of Ice and if protobuf is fixed. At the time I started this, Ice was not a part of vcpkg and I didn't want to put in more time trying to side-load Ice if we aren't going to use it. The only platform I have seen positive results with the bash script I created is on Windows (with GitBash_x64). Once it has been tested as working for the platforms we support, I'd like to get started with project generation using cmake (Qt Creator, VS, C:B, etc...). I'm open to any comments, feedback, or ideas.

**Comment by Kissaki** [comment]
I’m trying it out, getting to know vcpkg. Making some changes, I'll suggest in a PR.

Didn't get to actually building murmur/mumble yet.

Given Ice has been our suggested extension point, I think we should rather add the build recipe to vcpkg than to drop ICE. If at all, we should mark and present it as deprecated for a while before removing.

**Comment by ZeroAbility** [comment]
That is certainly an option. The get_murmur-deps.sh should be working on
Windows using Git Bash as well as GNU/Linux distros with mesa3d dev libs.
It appears they are working on a port for mesa3d. I will attempt to update
the readme on the experimental repo sometime today.

https://github.com/Microsoft/vcpkg/issues/5480#issuecomment-468783828



Thank you,



Nik Reist

**Comment by ZeroAbility** [comment]
The CMake project has already been merged so this could probably be closed.
